<a href="https://colab.research.google.com/github/migaczdawid/data-science-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [2]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum()

In [3]:
price.sum()

4650.1

In [4]:
price.sum(axis = 0 ) # parametr axis mówi po której osi nam zliczyć x czy y? Dostaniemy wówczas sumę albo wszystkich wierszy albo kolumn

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [5]:
price.sum(axis = 1 ) # parametr axis mówi po której osi nam zliczyć x czy y? Dostaniemy wówczas sumę albo wszystkich wierszy albo kolumn

array([1049.7, 2049.4, 1551. ])

In [6]:
np.sum(price)

4650.1

In [7]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [8]:
np.sum(price, axis=1)

array([1049.7, 2049.4, 1551. ])

min ()

In [9]:
np.min(price) # najmniejszy element w tablicy

11.7

In [10]:
np.min(price, axis = 0) # najmniejszy element w kolumnie

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [ ]:
np.min(price, axis=1) # najmniejszy element w wierszu

max()

In [11]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])