<a href="https://colab.research.google.com/github/migaczdawid/data-science-bootcamp/blob/main/01_wprowadzenie/numpy_01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# w razie braku zainstalowanej wersji dajemy komendę pip instal numpy
import numpy as np
np.__version__

'1.21.6'

In [ ]:
# Funkcja dir(X) sprawdza jakie mamy atrybuty oraz metody w bibliotece numpy, 
# jak nie korzystasz z czegoś to zamykaj X przed zapisme na Githuba
dir(np)

In [ ]:
# help(x.y) wywołuje nam pomoc dzięki, której mamy pokazane jak korzystać z metody
help(np.array)

1D Array // one dimensional array

In [ ]:
x = np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x) 

numpy.ndarray

In [ ]:
x.ndim #wymiar tablicy

1

In [ ]:
x.shape #kształt wymiary

(2,)

In [ ]:
x.size # liczba elementów w tablicy

2

In [ ]:
x.dtype # tym zmiennych w tablicy

dtype('int64')

In [ ]:
x = np.array([1.2,2.3,4.5])
x

array([1.2, 2.3, 4.5])

In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.size

4

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
x.shape

(2, 3)

3D Array 

In [6]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [7]:
x.ndim

3

In [8]:
x.shape

(2, 2, 3)

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x




In [12]:
x.ndim


3

In [14]:
x.shape

(3, 2, 3)

Typy Danych

In [15]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [16]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [17]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [18]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [22]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [23]:
A

array([1, 2, 3])

In [24]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [25]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [26]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [38]:
np.zeros(shape = (4,10)) # tablica z zerami

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.zeros(shape = (4,10), dtype='int') # możemy na sztywno ustawić typ w dtype

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
np.ones(shape=(5, 5)) # tablica 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.ones(shape=(5, 5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.full(shape=(3, 3), fill_value=4, dtype='int') # ustawiamy jakimi chcemy wypełniąc

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [44]:
np.arange(10) # działa jak range w pythonie, list(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(start=5, stop=10) # zaczyanmy od 5 a kończymy na 10

array([5, 6, 7, 8, 9])

In [46]:
np.arange(start=10, stop=100, step=10) # możemy ustawić również krok

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
np.arange(start=100, stop=10, step=-10) # krok może być ujemny ale za start musimy dać wyższą wartość

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [48]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [51]:
np.linspace(start=0, stop=1, num=11) # działa podobnie jak range ale parametr num mówi nam ile ma być elementów w tym przedziale równo rozłożonych

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [61]:
A = np.arange(15) # generujemy jeszcze raz do kolejnego ćwiczenia
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
A.reshape((3,5)) # zmienimy rozmiar tablicy podjąc wymiary (z,y,x)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
A.reshape((3, -1)) # dajemy -1 kiedy chcemy aby python sam nam posegregował elementy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
A.reshape((-1, 3)) # można też na odwrót

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [65]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [67]:
A + B # pamiętajmy aby rozmiar się zngadzał. Dodajemy elementy do siebie po elementach

array([6, 0, 7, 4])

In [69]:
A - B

array([0, 2, 1, 0])

In [70]:
A*B

array([ 9, -1, 12,  4])

In [71]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [76]:
np.add(A, B) # dodawanie

array([6, 0, 7, 4])

In [77]:
np.subtract(A, B) # odejmowanie

array([0, 2, 1, 0])

In [78]:
np.multiply(A, B) # mnożenie

array([ 9, -1, 12,  4])

In [79]:
np.divide(A, B) # dzielenie

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [72]:
A + 3

array([6, 4, 7, 5])

In [74]:
A - 3

array([ 0, -2,  1, -1])

In [75]:
A * 3

array([ 9,  3, 12,  6])

In [73]:
A / 3

array([1.        , 0.33333333, 1.33333333, 0.66666667])

In [ ]:
A + 3*B

Działania na macierzach 

In [80]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [81]:
X * Y # taki zapis pomnoży nam po elemencie ale nie macierzowo!

array([[6, 0],
       [2, 0]])

In [82]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [83]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [84]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [85]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [86]:
np.random.seed(0) # ustawiamy ziarno losowania abyśmy za każdym razem uzyskali taki sam wynik,

In [100]:
np.random.randn()

0.3113635032767906

In [105]:
np.random.randn(10)

array([-0.58582287,  0.93755884, -0.25460809,  0.97359871,  0.20728277,
        1.09964197,  0.93989698,  0.606389  ,  0.00176084, -0.99016014])

In [108]:
np.random.randn(10,4)

array([[ 1.87239408, -0.66110423, -1.18019102,  0.19764264],
       [ 0.41389998,  1.19732198,  1.88335386,  0.71422382],
       [ 2.28433335,  1.56410258,  0.61110371, -0.87736332],
       [-1.6210875 , -0.581673  , -0.53783395, -1.55602368],
       [-0.05446484, -1.81127879, -0.63117522, -0.92815918],
       [ 1.49072192,  0.19549934, -0.47160433,  1.81235465],
       [-2.29413748,  0.65120935, -1.13049645, -0.77734666],
       [ 1.11593845,  1.33945302, -1.76743365,  0.42441246],
       [ 1.08930905, -0.38418568,  0.63220141, -0.5496559 ],
       [ 0.52112574,  0.10834955,  0.26166848, -0.91475533]])

In [90]:
np.random.rand() # zwraca nam liczbę z przecidziału 0-1

0.9883738380592262

In [106]:
np.random.rand(10)

array([0.60639321, 0.0191932 , 0.30157482, 0.66017354, 0.29007761,
       0.61801543, 0.4287687 , 0.13547406, 0.29828233, 0.56996491])

In [109]:

np.random.rand(10,2)

array([[0.21331198, 0.51820071],
       [0.02566272, 0.20747008],
       [0.42468547, 0.37416998],
       [0.46357542, 0.27762871],
       [0.58678435, 0.86385561],
       [0.11753186, 0.51737911],
       [0.13206811, 0.71685968],
       [0.3960597 , 0.56542131],
       [0.18327984, 0.14484776],
       [0.48805628, 0.35561274]])

In [113]:
np.random.randint(10) # losujemy liczbę z przedziału od 0 do n

6

In [ ]:
np.random.randint(low=10, high=101) # parametr startowy oraz końcowy

In [114]:
np.random.randint(low=10, high=101, size=10) # size ile elementów

array([63, 58, 69, 90, 36, 45, 68, 59, 83, 54])

In [116]:
np.random.choice([4, 2, 1, 3, 5]) # losowy element z przedziału podanego przez USERA

4

In [117]:
np.random.choice(['python', 'java', 'sql']) # losowy element tekstowy

'java'

In [118]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.random.shuffle(data) # przetasuje nam liczby
data

array([7, 9, 1, 0, 6, 3, 2, 5, 8, 4])

Podstawowe funkcje


In [123]:
np.exp(1) 

2.718281828459045

In [124]:
np.sqrt(9)

3.0

In [127]:
np.all([2, 3, 1]) # bada każdy element i sprawdza czy każdy element zróci True, jak każdy zwroici to metoda zwróci True

True

In [129]:
np.any([0, 1, 0]) # bada każdy element i sprawdza czy jaki kolwiek element zróci True, jak choć jeden zwroici to metoda zwróci True

True

In [134]:
bool(1.3) # zwraca nam wartość logiczną elementu. Dla 0 to False a dla każdego elementu różnego od zera to True

True

In [135]:
A = np.random.rand(5)
A

array([0.14814086, 0.98182939, 0.47837031, 0.49739137, 0.63947252])

In [138]:
np.argmax(A) # wyciąga INDEX gdzie nasza funkcja przyjmuje wartość największą

1

In [140]:
A[np.argmax(A)] # wycinanie elementu

0.9818293898182532

In [ ]:
np.argmin(A) # wyciąga INDEX gdzie nasza funkcja przyjmuje wartość najmniejszą

In [142]:
np.argsort(A) # funkcja pozwala nam sortować elementy podając INDEX elementu, od najmniejszego do największego, pomaga w zwracaniu np 2 najprawdopodobniejszych klas

array([0, 2, 3, 4, 1])

In [143]:
np.max(A) # wartość największa

0.9818293898182532

In [147]:
np.min(A) # wartość najmniejsza

0.14814086094816503

In [146]:
np.mean(A) # średnia

0.5490408879407586

In [145]:
np.median(A) # mediana

0.4973913654986627

In [144]:
np.std(A) # odchylenie standardowe

0.2697653063679378

Indeksowanie, Wycinanie

In [148]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [149]:
A[2]

2

In [150]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [151]:
A[:2]

array([0, 1])

In [153]:
A[[0, 2]] # konkretne elementy

array([0, 2])

In [ ]:
A[-1]

In [154]:
A[10:15]

array([10, 11, 12, 13, 14])

In [155]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [164]:
A[0] # wycinamy konkretny wiersz

array([0, 1, 2, 3, 4])

In [ ]:
A[:0] # wycinamy konkretną kolumnę

In [165]:
A[:-1] # wycinamy ostatnią kolumnę

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A[1,1] #wycinamy konkretny element

In [ ]:
A[1:3, 1:4] # wycinamy fragment tablicy 

In [ ]:
A[1, 2] = 14 # przypisywanie nowych wartości do tablicy
A

Iteracja po tablicach


In [166]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [167]:
# Iteracja po wierszach
for row in A: 
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
# Iteracja po konkretnych elementach z wiersza
for row in A: 
    print(row[0]) # w nawiasie[] index naszego wiersza

In [168]:
# Iteracja po kolumnach // Iteracja po np. 3 pierwszych elementach każdego wiersza
for row in A:
    print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [169]:
# Iteracja po każdym elemencie tablicy. Musimy użyć atrybutu .flat który wypłaszczy nam tablicę
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [170]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [171]:
A.shape

(4, 5)

In [173]:
A.reshape(5,4) # zmiana rozmiaru tablicy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [176]:
A.ravel() # pozwala nam wypłaszczać nasze dane czyli postaci jednowymiarowej

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [177]:
A.T # transponowanie tablicy odbywa się jak transponowanie macierzy. Czyli zmieniamy kolumnę na wiersz a wiersz na kolumnę

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
Maski logiczne


In [178]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [179]:
A > 0 # robi nam Maskę Logiczną True/False

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [180]:
A[A > 0] # posiadając taką maskę możemy wyciąć dane które nas interesują

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [181]:
np.bitwise_and(A > -5, A < 5) # możemy łączyć warunki używając metody bitwise_and czyli nasz AND

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [182]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [183]:
np.bitwise_or(A < -5, A > 5) # możemy łączyć warunki używając metody bitwise_or czyli nasz OR

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])